# Generated by Django 4.1.3 on 2022-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('homeworld', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
            ],
        ),
    ]
